## Introducing Pandas Objects - Data Structures

In [ ]:
# Series: Population by Country Code
country_population = pd.Series(
        data=[61, 46, 11, 65, 10],
        index=["IT", "ES", "GR", "FR", "PO"],
        name="Country Population"
)
country_population

IT    61
ES    46
GR    11
FR    65
PO    10
Name: Country Population, dtype: int64

In [32]:
data = {
    "Name": [
    "Avery Bradley", "John Holland", "Jonas Jerebko",
    "Jordan Mickey", "Terry Rozier", "Jared Sullinger", "Evan Turner"
            ],
    "Team": ["Boston Celtics"] * 7,
    "Number": [0.0, 30.0, 8.0, None, 12.0, 7.0, 11.0],
    "Position": ["PG", "SG", "PF", "PF", "PG", "C", "SG"],
    "Age": [25.0, 27.0, 29.0, 21.0, 22.0, None, 27.0]
}

In [34]:
df_0 = pd.DataFrame(data)
df_0

              Name            Team  Number Position   Age
0    Avery Bradley  Boston Celtics     0.0       PG  25.0
1     John Holland  Boston Celtics    30.0       SG  27.0
2    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
3    Jordan Mickey  Boston Celtics     NaN       PF  21.0
4     Terry Rozier  Boston Celtics    12.0       PG  22.0
5  Jared Sullinger  Boston Celtics     7.0        C   NaN
6      Evan Turner  Boston Celtics    11.0       SG  27.0

In [ ]:
import seaborn as sns
import pandas as pd
titanic_data = sns.load_dataset('titanic')

In [2]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
titanic_data_sorted = titanic_data.sort_values(by='age', ascending=False)

In [16]:
titanic_data_sorted.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [19]:
survival_rate = titanic_data['survived'].mean()
print(survival_rate)

0.3838383838383838

In [22]:
def age_group(age):
    if pd.isna(age):
        return 'Unknown'
    elif age < 18:
        return 'Child'
    elif age < 65:
        return 'Adult'
    else:
        return 'Senior'

titanic_data_sorted['agegroup'] = titanic_data_sorted['age'].apply(age_group)

In [23]:
titanic_data_sorted.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,agegroup
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True,Senior
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True,Senior
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True,Senior
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True,Senior
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Senior

In [25]:
columns = titanic_data_sorted.select_dtypes(include=['float64', 'int64'])
columns.corr()

          survived    pclass       age     sibsp     parch      fare
survived  1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307
pclass   -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500
age      -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067
sibsp    -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651
parch     0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225
fare      0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000

In [26]:
titanic_data_sorted['embarked'].nunique()

3

In [29]:
titanic_data_sorted['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [30]:
titanic_data_sorted['fare_per_person'] = titanic_data_sorted['fare'] / (titanic_data_sorted['sibsp'] + titanic_data_sorted['parch'] + 1)