Lab #1: apply and map

In [2]:
import pandas as pd

In [3]:
data = { 'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
'Score': [88, 76, 95, 65, 70],
'Days_Off': [2, 5, 1, 8, 6]
}
df_lab1 = pd.DataFrame(data)

In [4]:
df_lab1

  Employee  Score  Days_Off
0    Alice     88         2
1      Bob     76         5
2  Charlie     95         1
3    David     65         8
4      Eva     70         6

In [5]:
def evaluate_performance(row):
    if row['Score'] >= 85 and row['Days_Off'] <= 3:
        return 'Excellent'
    elif row['Score'] >= 70 and row['Days_Off'] <= 5:
        return 'Good'
    elif row['Score'] >= 50:
        return 'Average'
    else:
        return 'Poor'

df_lab1['Performance'] = df_lab1.apply(evaluate_performance, axis=1)

In [6]:
df_lab1

  Employee  Score  Days_Off Performance
0    Alice     88         2   Excellent
1      Bob     76         5        Good
2  Charlie     95         1   Excellent
3    David     65         8     Average
4      Eva     70         6     Average

In [7]:
def categorize_score(score):
    return 'High' if score >= 80 else 'Low'

df_lab1['Score_Category'] = df_lab1['Score'].map(categorize_score)
df_lab1

  Employee  Score  Days_Off Performance Score_Category
0    Alice     88         2   Excellent           High
1      Bob     76         5        Good            Low
2  Charlie     95         1   Excellent           High
3    David     65         8     Average            Low
4      Eva     70         6     Average            Low

In [8]:
import seaborn as sns
titanic_data = sns.load_dataset('titanic')

KeyboardInterrupt:

In [ ]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
titanic_data.sort_values(by='age', ascending=False, inplace=True)

In [ ]:
titanic_data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [ ]:
overall_survival_rate = titanic_data['survived'].mean()
overall_survival_rate

0.3838383838383838

In [ ]:
def age_group(age):
    if age < 18:
        return 'Child'
    elif age < 65:
        return 'Adult'
    else:
        return 'Senior'
    
titanic_data['age_group'] = titanic_data['age'].map(age_group)

In [ ]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True,Senior
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True,Senior
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True,Senior
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True,Senior
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Senior

In [ ]:
columns = titanic_data.select_dtypes(include=['float64', 'int64'])
columns.corr()

          survived    pclass       age     sibsp     parch      fare
survived  1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307
pclass   -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500
age      -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067
sibsp    -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651
parch     0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225
fare      0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000

In [ ]:
titanic_data['embarked'].nunique()

3

In [ ]:
titanic_data['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
titanic_data['Fare_per_person'] = titanic_data['fare'] / (titanic_data['sibsp'] + titanic_data['parch'] + 1)

In [ ]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group,Fare_per_person
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True,Senior,30.0000
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True,Senior,7.7750
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True,Senior,49.5042
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True,Senior,34.6542
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Senior,7.7500

In [ ]:
retail_data = pd.read_csv("/Users/thutrang/Desktop/Code/NEU/DataPrepVisualize/Data/OnlineRetail.csv")

In [ ]:
retail_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,539993,22386,JUMBO BAG PINK POLKADOT,10,2011-01-04 10:00:00,1.95,13313.0,United Kingdom
1,539993,21499,BLUE POLKADOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
2,539993,21498,RED RETROSPOT WRAP,25,2011-01-04 10:00:00,0.42,13313.0,United Kingdom
3,539993,22379,RECYCLING BAG RETROSPOT,5,2011-01-04 10:00:00,2.10,13313.0,United Kingdom
4,539993,20718,RED RETROSPOT SHOPPER BAG,10,2011-01-04 10:00:00,1.25,13313.0,United Kingdom